---

- name: Install fish
  community.general.homebrew:
    name: fish
    state: present

- name: Change user shell to fish
  become: yes
  user:
    name: "{{USER_NAME}}"
    shell: /opt/homebrew/bin/fish

- name: Create fish dir for functions
  file:
    path: "{{ HOME_DIR }}/.config/fish/functions"
    state: directory

- name: copy fish config
  copy:
    src: config.fish
    dest: "{{ HOME_DIR }}/.config/fish/config.fish"

- name: copy custom functions
  copy:
    src: functions/
    dest: "{{HOME_DIR}}/.config/fish/functions/"
