---

- name: Create cursor config directory
  file:
    path: "{{ HOME_DIR }}/.cursor"
    state: directory

- name: Create Cursor User directory
  file:
    path: "{{ HOME_DIR }}/Library/Application Support/Cursor/User"
    state: directory

- name: Copy Cursor settings files
  copy:
    src: "settings.json"
    dest: "{{ HOME_DIR }}/Library/Application Support/Cursor/User/settings.json"

- name: Copy Cursor keybindings files
  copy:
    src: "keybindings.json"
    dest: "{{ HOME_DIR }}/Library/Application Support/Cursor/User/keybindings.json"

- name: Install Cursor extensions
  command: cursor --install-extension {{ item }}
  args:
    creates: "{{ HOME_DIR }}/.cursor/extensions/{{ item }}"
  with_lines: cat "{{ role_path }}/files/extensions.txt" 
