---

- name: Create yabai dir
  file:
    path: "{{ HOME_DIR }}/.config/yabai"
    state: directory

- name: copy yabai scripts
  copy:
    src: yabairc
    dest: "{{ HOME_DIR }}/.config/yabai/yabairc"

- name: start yabai service
  shell: "yabai --start-service"
