---

# https://get-coursier.io/docs/cli-installation.html#linux-macos

- name: Tap coursier/formulas
  homebrew_tap:
    name: coursier/formulas

- name: Install coursier
  homebrew:
    name: coursier/formulas/coursier
    state: present


- name: setup coursier
  shell: "cs setup"
