---

# https://get-coursier.io/docs/cli-installation.html#linux-macos

- name: Install coursier
  community.general.homebrew:
    name: "coursier/formulas/coursier"
    state: present
  # notify: 
  #   - Install scala tools
  #Setup scala manually: cs setup
  #Do not add Coursier PATH to ~/.profile.
  #It is added in fish config
