---

- name: Create ghostty config directory
  file:
    path: "{{ HOME_DIR }}/.config/ghostty"
    state: directory
    mode: "0755"

- name: Copy ghostty background image
  copy:
    src: bg-blurred-darker.png
    dest: "{{ HOME_DIR }}/.config/ghostty/bg-blurred-darker.png"
    mode: "0644"

- name: Copy ghostty configuration file
  copy:
    src: config
    dest: "{{ HOME_DIR }}/.config/ghostty/config"
    mode: "0644"
