---

- name: Install user tools
  community.general.homebrew:
    name: "{{USER_PACKAGES}}"
    state: present

- name: Install ui user tools
  community.general.homebrew_cask:
    name: "{{USER_UI_TOOLS}}"
    state: present

